baseUrl=https://demo5.cybersoft.edu.vn

browser=chrome

timeout=30000
# ---------------------LOGIN--------------------------
#valid user
login.email=testing06@gmail.com
login.password=123456

login.email1=testing08@gmail.com
login.password1=123456

#invalid user
login.invalid.email=testing06@gmail.com
login.invalid.password=11111111111111111

# ---------------------REGISTER--------------------------
#Registration failed - email already exists
register.name=Tuong Vi
register.existing.email=testing06@gmail.com
register.password=123456
register.phone=0823800800
register.birthday=December 24, 2020
register.gender=Nam