baseUrl=https://demo5.cybersoft.edu.vn

browser=chrome

timeout=30000
# ---------------------LOGIN--------------------------
#valid user
login.email=
login.password=

login.email1=
login.password1=

#invalid user
login.invalid.email=
login.invalid.password=

# ---------------------REGISTER--------------------------
#Registration failed - email already exists
register.name=
register.existing.email=
register.password=
register.phone=
register.birthday=
register.gender=